### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by ktheory** [kickstarter/build-ubuntu-ami#25]
I'm no longer maintaining the project. If you're interested in maintaining this project, please comment to that effect below.

I'd grant you access to publish new gem versions. I ask that you keep me as a gem author.

(I've switched to [Packer](https://packer.io), which I recommend.)

**Comment by nikolay** [comment]
@ktheory I would be happy to. There are bunch of forks with changes that make sense to get merged and, also, I think, it would be nice to switch to AWS SDK from Fog. My username on RubyGems is the same as here.

**Comment by ktheory** [comment]
@nikolay You got it! Thank you.
